export const INIT_APP = 'INIT_APP';
export const FECTH_DETAILS = 'FECTH_DETAILS';
export const FECTH_DETAILS_SUCCESS = 'FECTH_DETAILS_SUCCESS';
export const FECTH_DETAILS_FAILED = 'FECTH_DETAILS_FAILED';
export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const FETCH_SINGLE_USER_DETAILS = 'FETCH_SINGLE_USER_DETAILS';
export const UPDATE_SINGLE_USER_DETAILS = 'UPDATE_SINGLE_USER_DETAILS';